name: ci

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            nanreh/portpusher
          tags: |
            type=semver,pattern={{version}}
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Go build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build "-ldflags=-s -w" -o build/portpusher-amd64 main.go
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build "-ldflags=-s -w" -o build/portpusher-arm64 main.go
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}